'use strict';
const gulp = require('gulp');
const concat = require('gulp-concat');
const uglify = require('gulp-uglify');
const rename = require('gulp-rename');
gulp.task('example', () => {
  return gulp.src('scripts/*.js') // alle JavaScript-Dateien ...
    .pipe(concat('all.js'))       // ... zusammenfügen ...
    .pipe(gulp.dest('dist'))      // ... in einen Zielordner kopieren ...
    .pipe(rename('all.min.js'))   // ... die Datei umbenennen ...
    .pipe(uglify())               // ... minifizieren ...
    .pipe(gulp.dest('dist'));     // ... und die minifizierte Datei kopieren
});
gulp.task('default', ['example']);