'use strict';
const stack = [];             // Deklaration eines ganz normalen Arrays
stack.push(1);              // Hinzufügen eines Elements ...
stack.push(2);              // ... und noch eines ...
stack.push(3);              // ... und noch eines ...
stack.push(4, 5, 6, 7, 8);  // ... und direkt mehrere auf einen Schlag
console.log(stack.pop());   // Zurückgegeben wird das zuletzt hinzugefügte
                            // Element, die 8.