'use strict';
let result = 5;
result += 11; // Die Variable hat jetzt den Wert 16 ...
result -= 1;  // ... jetzt den Wert 15 ...
result /= 3;  // ... jetzt den Wert 5 ...
result *= 4;  // ... jetzt den Wert 20 ...
result %= 5;  // ... und jetzt den Wert 0.