'use strict';
const values = [        // ein Array ...
  'Max Mustermann',   // ... mit einer Zeichenkette ...
  22,                 // ... einer Zahl ...
  true                // ... und einem booleschen Wert
];