function init() {
  var fahrzeug = {                        // Dieses Objekt ...
    fahren: function() {                  // ... dient als ...
      console.log('Fahrzeug fahren');     // ... Prototyp.
    }
  }
  var fahrrad = Object.create(fahrzeug);
  fahrrad.fahren();
  var kfz = Object.create(fahrzeug);      // Objekte erben Methoden ...
  kfz.tanken = function() {               // ... und können weitere ...
    console.log('Fahrzeug tanken');       // ... Methoden und ...
  }                                       // ... Eigenschaften definieren.
  kfz.tanken();
  kfz.fahren();
}